import 'vite-plus/test/config'

import { defineConfig } from 'vite-plus'

export default defineConfig({
	check: {
		fmt: false,
	},
	test: {
		environment: 'node',
		include: ['scripts/**/*.test.ts'],
		exclude: [
			'**/.convex/**',
			'**/.data/**',
			'**/.repos/**',
			'**/dist/**',
			'**/node_modules/**',
			'**/target/**',
		],
		hookTimeout: 60_000,
		testTimeout: 60_000,
	},
	staged: {
		'*': 'vp fmt',
	},
	fmt: {
		semi: false,
		singleQuote: true,
		useTabs: true,
		ignorePatterns: [
			'.convex/**',
			'.data/**',
			'.repos/**',
			'.turbo/**',
			'**/.nuxt/**',
			'**/.output/**',
			'**/dist/**',
			'**/node_modules/**',
			'**/target/**',
			'convex/_generated/**',
			'pnpm-lock.yaml',
			'*.tsbuildinfo',
		],
		sortPackageJson: {},
	},
	lint: {
		ignorePatterns: [
			'.convex/**',
			'.data/**',
			'.repos/**',
			'.turbo/**',
			'**/.nuxt/**',
			'**/.output/**',
			'**/dist/**',
			'**/node_modules/**',
			'**/target/**',
			'convex/_generated/**',
		],
		plugins: ['eslint', 'oxc', 'typescript', 'unicorn'],
		categories: {
			correctness: 'warn',
			perf: 'warn',
			suspicious: 'warn',
		},
		rules: {
			'eslint/no-await-in-loop': 'off',
			'eslint/no-shadow': 'off',
			'eslint/no-underscore-dangle': 'off',
			'eslint/preserve-caught-error': 'off',
			'oxc/no-map-spread': 'off',
			'typescript/consistent-return': 'off',
			'typescript/no-base-to-string': 'off',
			'typescript/no-duplicate-type-constituents': 'off',
			'typescript/no-floating-promises': 'off',
			'typescript/no-implied-eval': 'off',
			'typescript/no-meaningless-void-operator': 'off',
			'typescript/no-redundant-type-constituents': 'off',
			'typescript/no-unnecessary-boolean-literal-compare': 'off',
			'typescript/no-unnecessary-type-arguments': 'off',
			'typescript/no-unnecessary-type-assertion': 'off',
			'typescript/no-unnecessary-type-conversion': 'off',
			'typescript/no-unnecessary-type-parameters': 'off',
			'typescript/no-unsafe-type-assertion': 'off',
			'typescript/await-thenable': 'off',
			'typescript/require-array-sort-compare': 'off',
			'typescript/restrict-template-expressions': 'off',
			'typescript/unbound-method': 'off',
			'unicorn/consistent-function-scoping': 'off',
			'unicorn/no-array-reverse': 'off',
			'unicorn/no-array-sort': 'off',
			'unicorn/no-instanceof-builtins': 'off',
			'unicorn/no-useless-fallback-in-spread': 'off',
			'unicorn/prefer-add-event-listener': 'off',
			'unicorn/prefer-set-has': 'off',
		},
		options: {
			typeAware: false,
			typeCheck: false,
		},
	},
})
