/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: fdc4a2c743c28877cb6bc583f512397c)
interface __BaseEnv_Env {
	DB: D1Database
	FILES: R2Bucket
	FRIENDS: DurableObjectNamespace<import('./index').FriendsHub>
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import('./index')
		durableNamespaces: 'FriendsHub'
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
